version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      - image: postgres:10.2
        ports:
          - "5432:15432"
        environment:
          - POSTGRES_USER=voyage
          - POSTGRES_DB=voyage_test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            pip install --user pipenv
            PATH=$PATH:~/.local/bin/ pipenv install --dev

      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run lint
          command: |
            PATH=$PATH:~/.local/bin/ make lint

      - run:
          name: Run tests
          command: |
            PATH=$PATH:~/.local/bin/ make test
