version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install --user pipenv
            PATH=$PATH:~/.local/bin/ pipenv install --dev

      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run lint
          command: |
            PATH=$PATH:~/.local/bin/ make lint
